name: Deploy FastAPI to AWS Lambda

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn
        pip install -r requirements.txt

    - name: Package Lambda function
      run: |
        mkdir -p package
        pip install --target ./package fastapi uvicorn
        cp -r * package/
        cd package
        zip -r ../lambda_function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name fast_test --zip-file fileb://lambda_function.zip
